version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ./volumes/main.conf:/etc/nginx/modsec/main.conf
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/error403.html:/etc/nginx/html/error403.html
  bwapp:
    image: hackersploit/bwapp-docker
    container_name: bwapp
    hostname: bwapp

