services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./volumes/main.conf:/etc/nginx/modsec/main.conf
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/error403.html:/etc/nginx/html/error403.html
  bwapp:
    image: hackersploit/bwapp-docker
    container_name: bwapp
    hostname: bwapp
  web-dvwa:
    image: vulnerables/web-dvwa
    container_name: web-dvwa
    hostname: web-dvwa
   

